# Data parameters
dataset:
  seq_folder: C:/Users/jacop/Desktop/research_fellowship/16bit_tifs
  input_size: [128,128]
  directory: /home/jaltieri/ddpmx/dataset128

model:
  in_ch: 1
  out_ch: 1
  resolution: 128
  num_res_blocks: 2
  ch: 128
  ch_mult: [1, 1, 2, 2, 4]
  attn_resolutions: [16]
  dropout: 0.1
  resamp_with_conv: True
  max_timesteps: 1000

training:
  num_epochs: 50
  learning_rate: 0.0001
  batch_size: 16
  cos_annealing_t_max: 100